### ISSUE TITLE
how to format syntax properly?

### ISSUE THREAD

**Issue by karlp** [j123b567/scpi-parser#13]
I'm a bit stuck trying to figure out how to write the command syntax, and debugging through the pattern matching isn't getting me very far.

I've got syntax like so: (Trying to match a GW Instek Function Generator's syntax for compatibility)
```
1  OUTPut[1|2] {OFF|ON}
2  OUTPut[1|2]?
3  OUTPut[1|2]:LOAD {DEFault|INFinity}
4  OUTPut[1|2]:LOAD?
```

I can get _parts_ of this to work, but not even close to all together.  Not even just command 2.  Have you got any tips on how to construct the scpi-parser syntaxes for this sort of thing?

**Comment by j123b567** [comment]
Arbitrary program data is cleanly implemented in experimental branch. I don't want to merge support for master branch, because of limited SCPI_Input functionality, that can't skip <nl> in arbitrary data.

Command OUTPut#:MODulation#:FM# is now possible but implementation is unfinished - described in #16 

All other problems from this issue are clear or implemented so closing it.
