### ISSUE TITLE
SCPI-99:6.2.5.2 Multiple Identical Capabilities

### ISSUE THREAD

**Issue by manuelk2007** [j123b567/scpi-parser#16]
Hello,
I'm wondering how to parse parameter in the command.

Here is an example: SENSe[n][:CHANnel]:FUNCtion:RESult:IND?

N could be 1,2,3,4 for example. I don't want to create four patterns for this.
Is it possible with the current version of this great parser?

Thank you in advance.

With kind regards

Manuel

**Comment by j123b567** [comment]
Now it is possible to have pattern OUT#:FREQuency
and commands OUT1:FREQ, OUT2:FREQ and OUT:FREQ

Unsupported range is up to user

In handler function, just call SCPI_CommandNumbers and it will fill
appropriate array

**Comment by 1nfused** [comment]
Hello,

would it be possible to get a test example or some kind of documentation regarding this issue? I am trying to implement OUT#:FREQuency but I don't know how to parse out the numbers (e.g.:  OUT1:FREQ and  OUT2:FREQ).

Thanks in advance!

**Comment by j123b567** [comment]
There is an example in `scpi-def.c`

pattern:

~~~~c
{.pattern = "TEST#:NUMbers#", .callback = TEST_Numbers,},
~~~~

callback
~~~~c
static scpi_result_t TEST_Numbers(scpi_t * context) {
    int32_t numbers[2];

    SCPI_CommandNumbers(context, numbers, 2);

    fprintf(stderr, "TEST numbers %d %d\r\n", numbers[0], numbers[1]);

    return SCPI_RES_OK;
}
~~~~

Because there are two `#` in pattern, expected size of `numbers` array is `2` and third parameter is also `2`.
If you call for example
~~~~
TEST2:NUM3
> TEST numbers 2 3

TEST:NUM3
> TEST numbers 1 3

TEST:NUM
> TEST numbers 1 1
~~~~

**Comment by j123b567** [comment]
I have also updated documentation accordingly. http://j123b567.github.io/scpi-parser/api/scpi_commandnumbers/

**Comment by 1nfused** [comment]
Thank you very much for these clarifications :)
