### ISSUE TITLE
Including inc/scpi/config.h in inc/scpi/scpi.h

### ISSUE THREAD

**Issue by andrey-nakin** [j123b567/scpi-parser#32]
Can you include `inc/scpi/config.h` by `inc/scpi/scpi.h`? I need `SCPI_doubleToStr` macro in my code and I don't want to include anything but `scpi.h`.

**Comment by j123b567** [comment]
I will do some changes and renaming. I don't want to make this macro public, but I can make public `doubleToStr` function from `utils.c` with name `SCPI_doubleToStr`. I don't like the situation in the `config.h`, because all macros are badly named.

It will take some time to make these changes.
For you, nothing will change. Just `SCPI_doubleToStr` will not be macro but function. You can use `#include "scpi/config.h"` until I fix this.

**Comment by andrey-nakin** [comment]
Thank you for response. I need `doubleToStr` or similar in SCPI handlers like `CONF?`.

**Comment by j123b567** [comment]
Sorry, I must change the name of the function. Now it is `SCPI_DoubleToStr` with big "D" to corespond with other names used in the library. I also make public `SCPI_LongToStr`.
