### ISSUE TITLE
SCPI_ExprChannelListEntry() crashes with whitespaces

### ISSUE THREAD

**Issue by koeart** [j123b567/scpi-parser#57]
If you enter a whitespace in your channel list, e. g. `(@1, 2)` instead of `(@1,2)`, result of `SCPI_ExprChannelListEntry` == SCPI_EXPR_ERROR and the parser get's somehow messed up, but it doesn't throw an error.

**Comment by j123b567** [comment]
Strictly speaking, spaces are not allowed in channel list.

If result of `SCPI_ExprChannelListEntry` is `SCPI_EXPR_ERROR`, then you can't  read other values returned by this function, because they are some random data.

Bug is, that it just return `SCPI_EXPR_ERROR` and does not set SCPI error.

After solving this, we can extend channel list parsing not to be so strict and allow some whitespaces.
