### ISSUE TITLE
Problem with SYSTem:ERRor[:NEXT]?

### ISSUE THREAD

**Issue by ASealion** [j123b567/scpi-parser#94]
Hi,

I'm using the SCPI parser without any modifications and found a"strange" behavior with the Error List:

At first I send 3 invalid commands to the parser (for example)
Command
`q`
Answer
`**ERROR: -113, "Undefined header"<\r><\n>`

is is as I expect the parser to handle the unknown command

When I now start to query the the error list:
Query
`syst:err:next?`
Answer
`-113,"Undefined header"<\r><\n>`

Second time:
Query
`syst:err:next?`
Answer
`-113,"Undefined header"<\r><\n>`

Third:
Query
`syst:err:next?`
Answer
`**ERROR: 0, "No error"<\r><\n>`
`-113,"Undefined header"<\r><\n>`

Why do I get the line with the two asterisks?

Regards Mike

**Comment by j123b567** [comment]
You are probably using example [test-interactive](https://github.com/j123b567/scpi-parser/blob/master/examples/test-interactive/main.c) and heare is a callback function `SCPI_Error()` which is responsive for `**ERROR: ...` output.

This function is supposed to be reimplemented by you, so you can control e.g. error LED or beeps. 

e.g. your implementation should look like this instead of writing some text to `stderr` like the example do.


    int SCPI_Error(scpi_t * context, int_fast16_t err) {
        (void) context;
        if (err != 0) {
            /* New error */
            beep();
            errorLedOn();
        } else {
            /* No more errors in the queue */
            errorLedOff();
        }
        return 0;
    }

**Comment by ASealion** [comment]
Ah, ok now I see the sense of the "Err 0"
